# Generated by Django 5.2.7 on 2025-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=140)),
                ('subheadline', models.CharField(blank=True, max_length=200)),
                ('cta_text', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='hero/')),
                ('overlay_opacity', models.FloatField(default=0.5)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
