# Generated by Django 5.2.7 on 2025-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome icon class, e.g. fa-globe', max_length=64)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Feature',
                'verbose_name_plural': 'About Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('subheading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Explore More', max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('features', models.ManyToManyField(blank=True, related_name='sections', to='home.aboutfeature')),
            ],
        ),
    ]
