# Generated by Django 5.2.7 on 2025-10-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutfeature_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfeature',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='Home-about/'),
        ),
    ]
