# Generated by Django 5.2.7 on 2025-10-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutfeature_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.TextField(blank=True)),
                ('call_text', models.CharField(default='Call for any query!', max_length=200)),
                ('overlay_color', models.CharField(blank=True, default='#000000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='FontAwesome icon class, e.g., fa-users', max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='home.factsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
