# Generated by Django 5.2.7 on 2025-11-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_factsection_factitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='We Are Trusted Logistics Company Since 2010', max_length=200)),
                ('subheading', models.CharField(default='Our Features', max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='features_bg/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homefeatures', to='home.homefeaturesection')),
            ],
        ),
    ]
