# Generated by Django 5.2.7 on 2025-11-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_partner_testimonial_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_top', models.CharField(default='Get A Quote', help_text='Small heading above the main title', max_length=200)),
                ('heading_main', models.CharField(default='Request A Free Quote!', help_text='Main heading displayed in bold', max_length=200)),
                ('description', models.TextField(help_text='Brief paragraph under the heading')),
                ('call_text', models.CharField(default='Call for any query!', help_text='Small caption above the phone number', max_length=200)),
                ('background_image', models.ImageField(blank=True, help_text='Optional background image for the quote section', null=True, upload_to='quote_section/')),
            ],
            options={
                'verbose_name': 'Quote Section',
                'verbose_name_plural': 'Quote Section',
            },
        ),
    ]
