# Generated by Django 5.2.7 on 2025-11-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_quotesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='isImageForPC',
            field=models.BooleanField(default=False),
        ),
    ]
