# Generated by Django 5.2.7 on 2025-11-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='We are Here for You', max_length=100)),
                ('description', models.TextField(default='We would love to hear from you! Use the contact information below to get to us and we’ll be in touch and reach out to you as soon as possible.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('opening_hours', models.CharField(default='Mon - Fri: 8:30 AM - 4:30 PM, Sat: 9:00 AM - 3:00 PM', max_length=255)),
            ],
        ),
    ]
