# Generated by Django 5.2.7 on 2025-11-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='isHQ',
            field=models.BooleanField(default=True),
        ),
    ]
