# Generated by Django 5.2.7 on 2025-11-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-ship', help_text='FontAwesome icon class, e.g., fas fa-ship', max_length=50)),
                ('small_title', models.CharField(default='Our Services', help_text='Small heading above the main title', max_length=120)),
                ('main_title', models.CharField(default='We Provide The Best Logistic Services For Your Needs', help_text='Main heading displayed in bold', max_length=200)),
                ('description', models.TextField(default='We offer cargo consolidation and de-consolidation, Cargo Sourcing, Door-to-door cargo delivery services across East Africa and Southern Africa. We provide best and affordable services in clearing and forwarding, to both Full Container Shipping Services (FCL) and Loose Cargo Shipping Services (LCL) to our customers.')),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Section',
            },
        ),
    ]
