# Generated by Django 5.2.7 on 2025-11-06 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardworkingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-ship', max_length=50)),
                ('small_title', models.CharField(default='HARDWORKING INDIVIDUALS', max_length=200)),
                ('main_title', models.CharField(default='Providing Excellent and Quality Customer Services', max_length=300)),
                ('description', models.TextField(default='All activities and operations are performed with high commitment and integrity while putting customers’ needs forward. Teamwork, reliability, innovativeness and professionalism make us one of the best in the industry.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hardworking/')),
            ],
            options={
                'verbose_name': 'Hardworking Section',
                'verbose_name_plural': 'Hardworking Sections',
            },
        ),
        migrations.CreateModel(
            name='HardworkingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-people-carry', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='service.hardworkingsection')),
            ],
            options={
                'verbose_name': 'Hardworking Feature',
                'verbose_name_plural': 'Hardworking Features',
                'ordering': ['order'],
            },
        ),
    ]
