# Generated by Django 5.2.7 on 2025-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_hardworkingsection_hardworkingfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='Client Testimonial', help_text='Small heading above the main title', max_length=100)),
                ('main_title', models.CharField(default='More Than 40+ Satisfied Client Testimonial', max_length=200)),
                ('description', models.TextField(default='Endorsements from more than 40 customers across East Africa and China vouching the quality and value of our services.')),
            ],
            options={
                'verbose_name': 'Testimonial Section Content',
                'verbose_name_plural': 'Testimonial Section Content',
            },
        ),
    ]
