# Generated by Django 5.2.7 on 2025-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('another_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('main_location', models.CharField(blank=True, max_length=255, null=True)),
                ('main_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('main_contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Main Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('primarycolor', models.CharField(default='#e41616', max_length=200)),
                ('secondarycolor', models.CharField(default='#e41616', max_length=200)),
                ('is_default_theme', models.BooleanField(default=False)),
            ],
        ),
    ]
