# Generated by Django 5.2.7 on 2025-11-06 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='About Us', max_length=120)),
                ('title', models.CharField(default='Driven by Trust. Powered by Innovation.', max_length=200)),
                ('description', models.TextField(default='GNM Cargo commenced business in 2010 and has maintained a strong presence in China for over 15 years, expanding operations across East Africa—Kenya and Uganda—through strategic subsidiaries offering seamless logistics solutions.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('background_overlay', models.BooleanField(default=True, help_text='Show dark overlay on the image')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='e.g. fas fa-ship', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='aboutus.aboutsection')),
            ],
            options={
                'verbose_name': 'About Feature',
                'verbose_name_plural': 'About Features',
                'ordering': ['id'],
            },
        ),
    ]
