# Generated by Django 5.2.7 on 2025-11-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutExperienceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-ship', help_text='FontAwesome icon class, e.g. fas fa-ship', max_length=100)),
                ('small_title', models.CharField(default='Experience', help_text='Small title above main heading', max_length=120)),
                ('heading', models.CharField(default='Experienced in East-Africa Logistic Services', max_length=255)),
                ('description', models.TextField(help_text='Main paragraph content about experience')),
                ('image', models.ImageField(blank=True, help_text='Image shown on the right side', null=True, upload_to='about_experience/')),
            ],
            options={
                'verbose_name': 'About Experience Section',
                'verbose_name_plural': 'About Experience Section',
            },
        ),
        migrations.CreateModel(
            name='AboutFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-check-circle', help_text='FontAwesome icon class', max_length=100)),
                ('text', models.CharField(max_length=120)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='aboutus.aboutexperiencesection')),
            ],
        ),
        migrations.CreateModel(
            name='AboutTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_icon', models.CharField(default='fas fa-quote-left', help_text='FontAwesome icon class for quote', max_length=100)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='aboutus.aboutexperiencesection')),
            ],
        ),
    ]
