# Generated by Django 5.2.7 on 2025-11-06 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_aboutexperiencesection_aboutfeatureitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalismSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-ship', help_text='FontAwesome icon class for the section', max_length=100)),
                ('small_title', models.CharField(default='Professionalism', help_text='Small title above main heading', max_length=120)),
                ('heading', models.CharField(default='Skillful and Professional Workers Doing The Job', max_length=255)),
                ('description', models.TextField(default='Here all the duties from receiving goods, baling, consolidation, de-consolidation, declaration to delivery by the ship is done with great care and expertise.')),
                ('image', models.ImageField(blank=True, help_text='Right side image', null=True, upload_to='professionalism/')),
            ],
            options={
                'verbose_name': 'Professionalism Section',
                'verbose_name_plural': 'Professionalism Section',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=120)),
                ('skill_value', models.PositiveIntegerField(default=0, help_text='Skill percentage value (0-100)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='aboutus.professionalismsection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
